//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for AggregateConfiguration complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="AggregateConfiguration"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UseServerCapabilitiesDefaults" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="TreatUncertainAsBad" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="PercentDataBad" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/&gt;
 *         &lt;element name="PercentDataGood" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/&gt;
 *         &lt;element name="UseSlopedExtrapolation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AggregateConfiguration", propOrder = {
    "useServerCapabilitiesDefaults",
    "treatUncertainAsBad",
    "percentDataBad",
    "percentDataGood",
    "useSlopedExtrapolation"
})
public class AggregateConfiguration {

    @XmlElement(name = "UseServerCapabilitiesDefaults")
    protected Boolean useServerCapabilitiesDefaults;
    @XmlElement(name = "TreatUncertainAsBad")
    protected Boolean treatUncertainAsBad;
    @XmlElement(name = "PercentDataBad")
    @XmlSchemaType(name = "unsignedByte")
    protected Short percentDataBad;
    @XmlElement(name = "PercentDataGood")
    @XmlSchemaType(name = "unsignedByte")
    protected Short percentDataGood;
    @XmlElement(name = "UseSlopedExtrapolation")
    protected Boolean useSlopedExtrapolation;

    /**
     * Gets the value of the useServerCapabilitiesDefaults property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseServerCapabilitiesDefaults() {
        return useServerCapabilitiesDefaults;
    }

    /**
     * Sets the value of the useServerCapabilitiesDefaults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseServerCapabilitiesDefaults(Boolean value) {
        this.useServerCapabilitiesDefaults = value;
    }

    /**
     * Gets the value of the treatUncertainAsBad property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTreatUncertainAsBad() {
        return treatUncertainAsBad;
    }

    /**
     * Sets the value of the treatUncertainAsBad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTreatUncertainAsBad(Boolean value) {
        this.treatUncertainAsBad = value;
    }

    /**
     * Gets the value of the percentDataBad property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPercentDataBad() {
        return percentDataBad;
    }

    /**
     * Sets the value of the percentDataBad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPercentDataBad(Short value) {
        this.percentDataBad = value;
    }

    /**
     * Gets the value of the percentDataGood property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPercentDataGood() {
        return percentDataGood;
    }

    /**
     * Sets the value of the percentDataGood property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPercentDataGood(Short value) {
        this.percentDataGood = value;
    }

    /**
     * Gets the value of the useSlopedExtrapolation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseSlopedExtrapolation() {
        return useSlopedExtrapolation;
    }

    /**
     * Sets the value of the useSlopedExtrapolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseSlopedExtrapolation(Boolean value) {
        this.useSlopedExtrapolation = value;
    }

}
