//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for BrowseResultMask&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="BrowseResultMask"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="None_0"/&gt;
 *     &lt;enumeration value="ReferenceTypeId_1"/&gt;
 *     &lt;enumeration value="IsForward_2"/&gt;
 *     &lt;enumeration value="NodeClass_4"/&gt;
 *     &lt;enumeration value="BrowseName_8"/&gt;
 *     &lt;enumeration value="DisplayName_16"/&gt;
 *     &lt;enumeration value="TypeDefinition_32"/&gt;
 *     &lt;enumeration value="All_63"/&gt;
 *     &lt;enumeration value="ReferenceTypeInfo_3"/&gt;
 *     &lt;enumeration value="TargetInfo_60"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "BrowseResultMask")
@XmlEnum
public enum BrowseResultMask {

    @XmlEnumValue("None_0")
    NONE_0("None_0"),
    @XmlEnumValue("ReferenceTypeId_1")
    REFERENCE_TYPE_ID_1("ReferenceTypeId_1"),
    @XmlEnumValue("IsForward_2")
    IS_FORWARD_2("IsForward_2"),
    @XmlEnumValue("NodeClass_4")
    NODE_CLASS_4("NodeClass_4"),
    @XmlEnumValue("BrowseName_8")
    BROWSE_NAME_8("BrowseName_8"),
    @XmlEnumValue("DisplayName_16")
    DISPLAY_NAME_16("DisplayName_16"),
    @XmlEnumValue("TypeDefinition_32")
    TYPE_DEFINITION_32("TypeDefinition_32"),
    @XmlEnumValue("All_63")
    ALL_63("All_63"),
    @XmlEnumValue("ReferenceTypeInfo_3")
    REFERENCE_TYPE_INFO_3("ReferenceTypeInfo_3"),
    @XmlEnumValue("TargetInfo_60")
    TARGET_INFO_60("TargetInfo_60");
    private final String value;

    BrowseResultMask(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static BrowseResultMask fromValue(String v) {
        for (BrowseResultMask c: BrowseResultMask.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
