//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ComplexNumberType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ComplexNumberType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Real" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="Imaginary" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexNumberType", propOrder = {
    "real",
    "imaginary"
})
public class ComplexNumberType {

    @XmlElement(name = "Real")
    protected Float real;
    @XmlElement(name = "Imaginary")
    protected Float imaginary;

    /**
     * Gets the value of the real property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getReal() {
        return real;
    }

    /**
     * Sets the value of the real property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setReal(Float value) {
        this.real = value;
    }

    /**
     * Gets the value of the imaginary property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getImaginary() {
        return imaginary;
    }

    /**
     * Sets the value of the imaginary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setImaginary(Float value) {
        this.imaginary = value;
    }

}
