//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for DataSetReaderDataType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="DataSetReaderDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="PublisherId" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}Variant" minOccurs="0"/&gt;
 *         &lt;element name="WriterGroupId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="DataSetWriterId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="DataSetMetaData" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}DataSetMetaDataType" minOccurs="0"/&gt;
 *         &lt;element name="DataSetFieldContentMask" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}DataSetFieldContentMask" minOccurs="0"/&gt;
 *         &lt;element name="MessageReceiveTimeout" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="KeyFrameCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="HeaderLayoutUri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SecurityMode" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}MessageSecurityMode" minOccurs="0"/&gt;
 *         &lt;element name="SecurityGroupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SecurityKeyServices" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfEndpointDescription" minOccurs="0"/&gt;
 *         &lt;element name="DataSetReaderProperties" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfKeyValuePair" minOccurs="0"/&gt;
 *         &lt;element name="TransportSettings" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ExtensionObject" minOccurs="0"/&gt;
 *         &lt;element name="MessageSettings" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ExtensionObject" minOccurs="0"/&gt;
 *         &lt;element name="SubscribedDataSet" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ExtensionObject" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataSetReaderDataType", propOrder = {
    "name",
    "enabled",
    "publisherId",
    "writerGroupId",
    "dataSetWriterId",
    "dataSetMetaData",
    "dataSetFieldContentMask",
    "messageReceiveTimeout",
    "keyFrameCount",
    "headerLayoutUri",
    "securityMode",
    "securityGroupId",
    "securityKeyServices",
    "dataSetReaderProperties",
    "transportSettings",
    "messageSettings",
    "subscribedDataSet"
})
public class DataSetReaderDataType {

    @XmlElementRef(name = "Name", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<String> name;
    @XmlElement(name = "Enabled")
    protected Boolean enabled;
    @XmlElement(name = "PublisherId")
    protected Variant publisherId;
    @XmlElement(name = "WriterGroupId")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer writerGroupId;
    @XmlElement(name = "DataSetWriterId")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer dataSetWriterId;
    @XmlElementRef(name = "DataSetMetaData", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<DataSetMetaDataType> dataSetMetaData;
    @XmlElement(name = "DataSetFieldContentMask")
    @XmlSchemaType(name = "unsignedInt")
    protected Long dataSetFieldContentMask;
    @XmlElement(name = "MessageReceiveTimeout")
    protected Double messageReceiveTimeout;
    @XmlElement(name = "KeyFrameCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long keyFrameCount;
    @XmlElementRef(name = "HeaderLayoutUri", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<String> headerLayoutUri;
    @XmlElement(name = "SecurityMode")
    @XmlSchemaType(name = "string")
    protected MessageSecurityMode securityMode;
    @XmlElementRef(name = "SecurityGroupId", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<String> securityGroupId;
    @XmlElementRef(name = "SecurityKeyServices", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfEndpointDescription> securityKeyServices;
    @XmlElementRef(name = "DataSetReaderProperties", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfKeyValuePair> dataSetReaderProperties;
    @XmlElementRef(name = "TransportSettings", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ExtensionObject> transportSettings;
    @XmlElementRef(name = "MessageSettings", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ExtensionObject> messageSettings;
    @XmlElementRef(name = "SubscribedDataSet", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ExtensionObject> subscribedDataSet;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the publisherId property.
     * 
     * @return
     *     possible object is
     *     {@link Variant }
     *     
     */
    public Variant getPublisherId() {
        return publisherId;
    }

    /**
     * Sets the value of the publisherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variant }
     *     
     */
    public void setPublisherId(Variant value) {
        this.publisherId = value;
    }

    /**
     * Gets the value of the writerGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWriterGroupId() {
        return writerGroupId;
    }

    /**
     * Sets the value of the writerGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWriterGroupId(Integer value) {
        this.writerGroupId = value;
    }

    /**
     * Gets the value of the dataSetWriterId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDataSetWriterId() {
        return dataSetWriterId;
    }

    /**
     * Sets the value of the dataSetWriterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDataSetWriterId(Integer value) {
        this.dataSetWriterId = value;
    }

    /**
     * Gets the value of the dataSetMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataSetMetaDataType }{@code >}
     *     
     */
    public JAXBElement<DataSetMetaDataType> getDataSetMetaData() {
        return dataSetMetaData;
    }

    /**
     * Sets the value of the dataSetMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataSetMetaDataType }{@code >}
     *     
     */
    public void setDataSetMetaData(JAXBElement<DataSetMetaDataType> value) {
        this.dataSetMetaData = value;
    }

    /**
     * Gets the value of the dataSetFieldContentMask property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataSetFieldContentMask() {
        return dataSetFieldContentMask;
    }

    /**
     * Sets the value of the dataSetFieldContentMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataSetFieldContentMask(Long value) {
        this.dataSetFieldContentMask = value;
    }

    /**
     * Gets the value of the messageReceiveTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMessageReceiveTimeout() {
        return messageReceiveTimeout;
    }

    /**
     * Sets the value of the messageReceiveTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMessageReceiveTimeout(Double value) {
        this.messageReceiveTimeout = value;
    }

    /**
     * Gets the value of the keyFrameCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getKeyFrameCount() {
        return keyFrameCount;
    }

    /**
     * Sets the value of the keyFrameCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setKeyFrameCount(Long value) {
        this.keyFrameCount = value;
    }

    /**
     * Gets the value of the headerLayoutUri property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHeaderLayoutUri() {
        return headerLayoutUri;
    }

    /**
     * Sets the value of the headerLayoutUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHeaderLayoutUri(JAXBElement<String> value) {
        this.headerLayoutUri = value;
    }

    /**
     * Gets the value of the securityMode property.
     * 
     * @return
     *     possible object is
     *     {@link MessageSecurityMode }
     *     
     */
    public MessageSecurityMode getSecurityMode() {
        return securityMode;
    }

    /**
     * Sets the value of the securityMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageSecurityMode }
     *     
     */
    public void setSecurityMode(MessageSecurityMode value) {
        this.securityMode = value;
    }

    /**
     * Gets the value of the securityGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSecurityGroupId() {
        return securityGroupId;
    }

    /**
     * Sets the value of the securityGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSecurityGroupId(JAXBElement<String> value) {
        this.securityGroupId = value;
    }

    /**
     * Gets the value of the securityKeyServices property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfEndpointDescription }{@code >}
     *     
     */
    public JAXBElement<ListOfEndpointDescription> getSecurityKeyServices() {
        return securityKeyServices;
    }

    /**
     * Sets the value of the securityKeyServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfEndpointDescription }{@code >}
     *     
     */
    public void setSecurityKeyServices(JAXBElement<ListOfEndpointDescription> value) {
        this.securityKeyServices = value;
    }

    /**
     * Gets the value of the dataSetReaderProperties property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfKeyValuePair }{@code >}
     *     
     */
    public JAXBElement<ListOfKeyValuePair> getDataSetReaderProperties() {
        return dataSetReaderProperties;
    }

    /**
     * Sets the value of the dataSetReaderProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfKeyValuePair }{@code >}
     *     
     */
    public void setDataSetReaderProperties(JAXBElement<ListOfKeyValuePair> value) {
        this.dataSetReaderProperties = value;
    }

    /**
     * Gets the value of the transportSettings property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ExtensionObject }{@code >}
     *     
     */
    public JAXBElement<ExtensionObject> getTransportSettings() {
        return transportSettings;
    }

    /**
     * Sets the value of the transportSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ExtensionObject }{@code >}
     *     
     */
    public void setTransportSettings(JAXBElement<ExtensionObject> value) {
        this.transportSettings = value;
    }

    /**
     * Gets the value of the messageSettings property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ExtensionObject }{@code >}
     *     
     */
    public JAXBElement<ExtensionObject> getMessageSettings() {
        return messageSettings;
    }

    /**
     * Sets the value of the messageSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ExtensionObject }{@code >}
     *     
     */
    public void setMessageSettings(JAXBElement<ExtensionObject> value) {
        this.messageSettings = value;
    }

    /**
     * Gets the value of the subscribedDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ExtensionObject }{@code >}
     *     
     */
    public JAXBElement<ExtensionObject> getSubscribedDataSet() {
        return subscribedDataSet;
    }

    /**
     * Sets the value of the subscribedDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ExtensionObject }{@code >}
     *     
     */
    public void setSubscribedDataSet(JAXBElement<ExtensionObject> value) {
        this.subscribedDataSet = value;
    }

}
