//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for DatagramWriterGroupTransportDataType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="DatagramWriterGroupTransportDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}WriterGroupTransportDataType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MessageRepeatCount" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/&gt;
 *         &lt;element name="MessageRepeatDelay" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatagramWriterGroupTransportDataType", propOrder = {
    "messageRepeatCount",
    "messageRepeatDelay"
})
public class DatagramWriterGroupTransportDataType
    extends WriterGroupTransportDataType
{

    @XmlElement(name = "MessageRepeatCount")
    @XmlSchemaType(name = "unsignedByte")
    protected Short messageRepeatCount;
    @XmlElement(name = "MessageRepeatDelay")
    protected Double messageRepeatDelay;

    /**
     * Gets the value of the messageRepeatCount property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMessageRepeatCount() {
        return messageRepeatCount;
    }

    /**
     * Sets the value of the messageRepeatCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMessageRepeatCount(Short value) {
        this.messageRepeatCount = value;
    }

    /**
     * Gets the value of the messageRepeatDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMessageRepeatDelay() {
        return messageRepeatDelay;
    }

    /**
     * Sets the value of the messageRepeatDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMessageRepeatDelay(Double value) {
        this.messageRepeatDelay = value;
    }

}
