//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for EndpointConfiguration complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="EndpointConfiguration"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OperationTimeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="UseBinaryEncoding" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="MaxStringLength" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="MaxByteStringLength" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="MaxArrayLength" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="MaxMessageSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="MaxBufferSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ChannelLifetime" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="SecurityTokenLifetime" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndpointConfiguration", propOrder = {
    "operationTimeout",
    "useBinaryEncoding",
    "maxStringLength",
    "maxByteStringLength",
    "maxArrayLength",
    "maxMessageSize",
    "maxBufferSize",
    "channelLifetime",
    "securityTokenLifetime"
})
public class EndpointConfiguration {

    @XmlElement(name = "OperationTimeout")
    protected Integer operationTimeout;
    @XmlElement(name = "UseBinaryEncoding")
    protected Boolean useBinaryEncoding;
    @XmlElement(name = "MaxStringLength")
    protected Integer maxStringLength;
    @XmlElement(name = "MaxByteStringLength")
    protected Integer maxByteStringLength;
    @XmlElement(name = "MaxArrayLength")
    protected Integer maxArrayLength;
    @XmlElement(name = "MaxMessageSize")
    protected Integer maxMessageSize;
    @XmlElement(name = "MaxBufferSize")
    protected Integer maxBufferSize;
    @XmlElement(name = "ChannelLifetime")
    protected Integer channelLifetime;
    @XmlElement(name = "SecurityTokenLifetime")
    protected Integer securityTokenLifetime;

    /**
     * Gets the value of the operationTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOperationTimeout() {
        return operationTimeout;
    }

    /**
     * Sets the value of the operationTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOperationTimeout(Integer value) {
        this.operationTimeout = value;
    }

    /**
     * Gets the value of the useBinaryEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseBinaryEncoding() {
        return useBinaryEncoding;
    }

    /**
     * Sets the value of the useBinaryEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseBinaryEncoding(Boolean value) {
        this.useBinaryEncoding = value;
    }

    /**
     * Gets the value of the maxStringLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxStringLength() {
        return maxStringLength;
    }

    /**
     * Sets the value of the maxStringLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxStringLength(Integer value) {
        this.maxStringLength = value;
    }

    /**
     * Gets the value of the maxByteStringLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxByteStringLength() {
        return maxByteStringLength;
    }

    /**
     * Sets the value of the maxByteStringLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxByteStringLength(Integer value) {
        this.maxByteStringLength = value;
    }

    /**
     * Gets the value of the maxArrayLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxArrayLength() {
        return maxArrayLength;
    }

    /**
     * Sets the value of the maxArrayLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxArrayLength(Integer value) {
        this.maxArrayLength = value;
    }

    /**
     * Gets the value of the maxMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxMessageSize() {
        return maxMessageSize;
    }

    /**
     * Sets the value of the maxMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxMessageSize(Integer value) {
        this.maxMessageSize = value;
    }

    /**
     * Gets the value of the maxBufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxBufferSize() {
        return maxBufferSize;
    }

    /**
     * Sets the value of the maxBufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxBufferSize(Integer value) {
        this.maxBufferSize = value;
    }

    /**
     * Gets the value of the channelLifetime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getChannelLifetime() {
        return channelLifetime;
    }

    /**
     * Sets the value of the channelLifetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChannelLifetime(Integer value) {
        this.channelLifetime = value;
    }

    /**
     * Gets the value of the securityTokenLifetime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSecurityTokenLifetime() {
        return securityTokenLifetime;
    }

    /**
     * Sets the value of the securityTokenLifetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSecurityTokenLifetime(Integer value) {
        this.securityTokenLifetime = value;
    }

}
