//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for ExceptionDeviationFormat&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="ExceptionDeviationFormat"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AbsoluteValue_0"/&gt;
 *     &lt;enumeration value="PercentOfValue_1"/&gt;
 *     &lt;enumeration value="PercentOfRange_2"/&gt;
 *     &lt;enumeration value="PercentOfEURange_3"/&gt;
 *     &lt;enumeration value="Unknown_4"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "ExceptionDeviationFormat")
@XmlEnum
public enum ExceptionDeviationFormat {

    @XmlEnumValue("AbsoluteValue_0")
    ABSOLUTE_VALUE_0("AbsoluteValue_0"),
    @XmlEnumValue("PercentOfValue_1")
    PERCENT_OF_VALUE_1("PercentOfValue_1"),
    @XmlEnumValue("PercentOfRange_2")
    PERCENT_OF_RANGE_2("PercentOfRange_2"),
    @XmlEnumValue("PercentOfEURange_3")
    PERCENT_OF_EU_RANGE_3("PercentOfEURange_3"),
    @XmlEnumValue("Unknown_4")
    UNKNOWN_4("Unknown_4");
    private final String value;

    ExceptionDeviationFormat(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ExceptionDeviationFormat fromValue(String v) {
        for (ExceptionDeviationFormat c: ExceptionDeviationFormat.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
