//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for HistoryUpdateType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="HistoryUpdateType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Insert_1"/&gt;
 *     &lt;enumeration value="Replace_2"/&gt;
 *     &lt;enumeration value="Update_3"/&gt;
 *     &lt;enumeration value="Delete_4"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "HistoryUpdateType")
@XmlEnum
public enum HistoryUpdateType {

    @XmlEnumValue("Insert_1")
    INSERT_1("Insert_1"),
    @XmlEnumValue("Replace_2")
    REPLACE_2("Replace_2"),
    @XmlEnumValue("Update_3")
    UPDATE_3("Update_3"),
    @XmlEnumValue("Delete_4")
    DELETE_4("Delete_4");
    private final String value;

    HistoryUpdateType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static HistoryUpdateType fromValue(String v) {
        for (HistoryUpdateType c: HistoryUpdateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
