//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ListOfSimpleAttributeOperand complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ListOfSimpleAttributeOperand"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SimpleAttributeOperand" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}SimpleAttributeOperand" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListOfSimpleAttributeOperand", propOrder = {
    "simpleAttributeOperand"
})
public class ListOfSimpleAttributeOperand {

    @XmlElement(name = "SimpleAttributeOperand", nillable = true)
    protected List<SimpleAttributeOperand> simpleAttributeOperand;

    /**
     * Gets the value of the simpleAttributeOperand property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the simpleAttributeOperand property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getSimpleAttributeOperand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleAttributeOperand }
     * </p>
     * 
     * 
     * @return
     *     The value of the simpleAttributeOperand property.
     */
    public List<SimpleAttributeOperand> getSimpleAttributeOperand() {
        if (simpleAttributeOperand == null) {
            simpleAttributeOperand = new ArrayList<>();
        }
        return this.simpleAttributeOperand;
    }

}
