//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for ModelChangeStructureVerbMask&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="ModelChangeStructureVerbMask"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NodeAdded_1"/&gt;
 *     &lt;enumeration value="NodeDeleted_2"/&gt;
 *     &lt;enumeration value="ReferenceAdded_4"/&gt;
 *     &lt;enumeration value="ReferenceDeleted_8"/&gt;
 *     &lt;enumeration value="DataTypeChanged_16"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "ModelChangeStructureVerbMask")
@XmlEnum
public enum ModelChangeStructureVerbMask {

    @XmlEnumValue("NodeAdded_1")
    NODE_ADDED_1("NodeAdded_1"),
    @XmlEnumValue("NodeDeleted_2")
    NODE_DELETED_2("NodeDeleted_2"),
    @XmlEnumValue("ReferenceAdded_4")
    REFERENCE_ADDED_4("ReferenceAdded_4"),
    @XmlEnumValue("ReferenceDeleted_8")
    REFERENCE_DELETED_8("ReferenceDeleted_8"),
    @XmlEnumValue("DataTypeChanged_16")
    DATA_TYPE_CHANGED_16("DataTypeChanged_16");
    private final String value;

    ModelChangeStructureVerbMask(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ModelChangeStructureVerbMask fromValue(String v) {
        for (ModelChangeStructureVerbMask c: ModelChangeStructureVerbMask.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
