//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for MonitoredItemCreateRequest complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="MonitoredItemCreateRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ItemToMonitor" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ReadValueId" minOccurs="0"/&gt;
 *         &lt;element name="MonitoringMode" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}MonitoringMode" minOccurs="0"/&gt;
 *         &lt;element name="RequestedParameters" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}MonitoringParameters" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MonitoredItemCreateRequest", propOrder = {
    "itemToMonitor",
    "monitoringMode",
    "requestedParameters"
})
public class MonitoredItemCreateRequest {

    @XmlElementRef(name = "ItemToMonitor", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ReadValueId> itemToMonitor;
    @XmlElement(name = "MonitoringMode")
    @XmlSchemaType(name = "string")
    protected MonitoringMode monitoringMode;
    @XmlElementRef(name = "RequestedParameters", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<MonitoringParameters> requestedParameters;

    /**
     * Gets the value of the itemToMonitor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ReadValueId }{@code >}
     *     
     */
    public JAXBElement<ReadValueId> getItemToMonitor() {
        return itemToMonitor;
    }

    /**
     * Sets the value of the itemToMonitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ReadValueId }{@code >}
     *     
     */
    public void setItemToMonitor(JAXBElement<ReadValueId> value) {
        this.itemToMonitor = value;
    }

    /**
     * Gets the value of the monitoringMode property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringMode }
     *     
     */
    public MonitoringMode getMonitoringMode() {
        return monitoringMode;
    }

    /**
     * Sets the value of the monitoringMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringMode }
     *     
     */
    public void setMonitoringMode(MonitoringMode value) {
        this.monitoringMode = value;
    }

    /**
     * Gets the value of the requestedParameters property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MonitoringParameters }{@code >}
     *     
     */
    public JAXBElement<MonitoringParameters> getRequestedParameters() {
        return requestedParameters;
    }

    /**
     * Sets the value of the requestedParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MonitoringParameters }{@code >}
     *     
     */
    public void setRequestedParameters(JAXBElement<MonitoringParameters> value) {
        this.requestedParameters = value;
    }

}
