//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for NegotiationStatus&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="NegotiationStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="InProgress_0"/&gt;
 *     &lt;enumeration value="Complete_1"/&gt;
 *     &lt;enumeration value="Failed_2"/&gt;
 *     &lt;enumeration value="Unknown_3"/&gt;
 *     &lt;enumeration value="NoNegotiation_4"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "NegotiationStatus")
@XmlEnum
public enum NegotiationStatus {

    @XmlEnumValue("InProgress_0")
    IN_PROGRESS_0("InProgress_0"),
    @XmlEnumValue("Complete_1")
    COMPLETE_1("Complete_1"),
    @XmlEnumValue("Failed_2")
    FAILED_2("Failed_2"),
    @XmlEnumValue("Unknown_3")
    UNKNOWN_3("Unknown_3"),
    @XmlEnumValue("NoNegotiation_4")
    NO_NEGOTIATION_4("NoNegotiation_4");
    private final String value;

    NegotiationStatus(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static NegotiationStatus fromValue(String v) {
        for (NegotiationStatus c: NegotiationStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
