//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for NodeTypeDescription complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="NodeTypeDescription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TypeDefinitionNode" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ExpandedNodeId" minOccurs="0"/&gt;
 *         &lt;element name="IncludeSubTypes" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="DataToReturn" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfQueryDataDescription" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeTypeDescription", propOrder = {
    "typeDefinitionNode",
    "includeSubTypes",
    "dataToReturn"
})
public class NodeTypeDescription {

    @XmlElementRef(name = "TypeDefinitionNode", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ExpandedNodeId> typeDefinitionNode;
    @XmlElement(name = "IncludeSubTypes")
    protected Boolean includeSubTypes;
    @XmlElementRef(name = "DataToReturn", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfQueryDataDescription> dataToReturn;

    /**
     * Gets the value of the typeDefinitionNode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ExpandedNodeId }{@code >}
     *     
     */
    public JAXBElement<ExpandedNodeId> getTypeDefinitionNode() {
        return typeDefinitionNode;
    }

    /**
     * Sets the value of the typeDefinitionNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ExpandedNodeId }{@code >}
     *     
     */
    public void setTypeDefinitionNode(JAXBElement<ExpandedNodeId> value) {
        this.typeDefinitionNode = value;
    }

    /**
     * Gets the value of the includeSubTypes property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeSubTypes() {
        return includeSubTypes;
    }

    /**
     * Sets the value of the includeSubTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeSubTypes(Boolean value) {
        this.includeSubTypes = value;
    }

    /**
     * Gets the value of the dataToReturn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfQueryDataDescription }{@code >}
     *     
     */
    public JAXBElement<ListOfQueryDataDescription> getDataToReturn() {
        return dataToReturn;
    }

    /**
     * Sets the value of the dataToReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfQueryDataDescription }{@code >}
     *     
     */
    public void setDataToReturn(JAXBElement<ListOfQueryDataDescription> value) {
        this.dataToReturn = value;
    }

}
