//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for OverrideValueHandling&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="OverrideValueHandling"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Disabled_0"/&gt;
 *     &lt;enumeration value="LastUsableValue_1"/&gt;
 *     &lt;enumeration value="OverrideValue_2"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "OverrideValueHandling")
@XmlEnum
public enum OverrideValueHandling {

    @XmlEnumValue("Disabled_0")
    DISABLED_0("Disabled_0"),
    @XmlEnumValue("LastUsableValue_1")
    LAST_USABLE_VALUE_1("LastUsableValue_1"),
    @XmlEnumValue("OverrideValue_2")
    OVERRIDE_VALUE_2("OverrideValue_2");
    private final String value;

    OverrideValueHandling(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static OverrideValueHandling fromValue(String v) {
        for (OverrideValueHandling c: OverrideValueHandling.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
