//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for PublishedDataItemsDataType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="PublishedDataItemsDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}PublishedDataSetSourceDataType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PublishedData" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfPublishedVariableDataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublishedDataItemsDataType", propOrder = {
    "publishedData"
})
public class PublishedDataItemsDataType
    extends PublishedDataSetSourceDataType
{

    @XmlElementRef(name = "PublishedData", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfPublishedVariableDataType> publishedData;

    /**
     * Gets the value of the publishedData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfPublishedVariableDataType }{@code >}
     *     
     */
    public JAXBElement<ListOfPublishedVariableDataType> getPublishedData() {
        return publishedData;
    }

    /**
     * Sets the value of the publishedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfPublishedVariableDataType }{@code >}
     *     
     */
    public void setPublishedData(JAXBElement<ListOfPublishedVariableDataType> value) {
        this.publishedData = value;
    }

}
