//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for PubSubState&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="PubSubState"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Disabled_0"/&gt;
 *     &lt;enumeration value="Paused_1"/&gt;
 *     &lt;enumeration value="Operational_2"/&gt;
 *     &lt;enumeration value="Error_3"/&gt;
 *     &lt;enumeration value="PreOperational_4"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "PubSubState")
@XmlEnum
public enum PubSubState {

    @XmlEnumValue("Disabled_0")
    DISABLED_0("Disabled_0"),
    @XmlEnumValue("Paused_1")
    PAUSED_1("Paused_1"),
    @XmlEnumValue("Operational_2")
    OPERATIONAL_2("Operational_2"),
    @XmlEnumValue("Error_3")
    ERROR_3("Error_3"),
    @XmlEnumValue("PreOperational_4")
    PRE_OPERATIONAL_4("PreOperational_4");
    private final String value;

    PubSubState(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static PubSubState fromValue(String v) {
        for (PubSubState c: PubSubState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
