//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ReadAtTimeDetails complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ReadAtTimeDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}HistoryReadDetails"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReqTimes" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfDateTime" minOccurs="0"/&gt;
 *         &lt;element name="UseSimpleBounds" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReadAtTimeDetails", propOrder = {
    "reqTimes",
    "useSimpleBounds"
})
public class ReadAtTimeDetails
    extends HistoryReadDetails
{

    @XmlElementRef(name = "ReqTimes", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfDateTime> reqTimes;
    @XmlElement(name = "UseSimpleBounds")
    protected Boolean useSimpleBounds;

    /**
     * Gets the value of the reqTimes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfDateTime }{@code >}
     *     
     */
    public JAXBElement<ListOfDateTime> getReqTimes() {
        return reqTimes;
    }

    /**
     * Sets the value of the reqTimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfDateTime }{@code >}
     *     
     */
    public void setReqTimes(JAXBElement<ListOfDateTime> value) {
        this.reqTimes = value;
    }

    /**
     * Gets the value of the useSimpleBounds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseSimpleBounds() {
        return useSimpleBounds;
    }

    /**
     * Sets the value of the useSimpleBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseSimpleBounds(Boolean value) {
        this.useSimpleBounds = value;
    }

}
