//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ServerDiagnosticsSummaryDataType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ServerDiagnosticsSummaryDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ServerViewCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="CurrentSessionCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="CumulatedSessionCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="SecurityRejectedSessionCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="RejectedSessionCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="SessionTimeoutCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="SessionAbortCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="CurrentSubscriptionCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="CumulatedSubscriptionCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="PublishingIntervalCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="SecurityRejectedRequestsCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="RejectedRequestsCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServerDiagnosticsSummaryDataType", propOrder = {
    "serverViewCount",
    "currentSessionCount",
    "cumulatedSessionCount",
    "securityRejectedSessionCount",
    "rejectedSessionCount",
    "sessionTimeoutCount",
    "sessionAbortCount",
    "currentSubscriptionCount",
    "cumulatedSubscriptionCount",
    "publishingIntervalCount",
    "securityRejectedRequestsCount",
    "rejectedRequestsCount"
})
public class ServerDiagnosticsSummaryDataType {

    @XmlElement(name = "ServerViewCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long serverViewCount;
    @XmlElement(name = "CurrentSessionCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long currentSessionCount;
    @XmlElement(name = "CumulatedSessionCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long cumulatedSessionCount;
    @XmlElement(name = "SecurityRejectedSessionCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long securityRejectedSessionCount;
    @XmlElement(name = "RejectedSessionCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long rejectedSessionCount;
    @XmlElement(name = "SessionTimeoutCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long sessionTimeoutCount;
    @XmlElement(name = "SessionAbortCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long sessionAbortCount;
    @XmlElement(name = "CurrentSubscriptionCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long currentSubscriptionCount;
    @XmlElement(name = "CumulatedSubscriptionCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long cumulatedSubscriptionCount;
    @XmlElement(name = "PublishingIntervalCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long publishingIntervalCount;
    @XmlElement(name = "SecurityRejectedRequestsCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long securityRejectedRequestsCount;
    @XmlElement(name = "RejectedRequestsCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long rejectedRequestsCount;

    /**
     * Gets the value of the serverViewCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getServerViewCount() {
        return serverViewCount;
    }

    /**
     * Sets the value of the serverViewCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setServerViewCount(Long value) {
        this.serverViewCount = value;
    }

    /**
     * Gets the value of the currentSessionCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCurrentSessionCount() {
        return currentSessionCount;
    }

    /**
     * Sets the value of the currentSessionCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCurrentSessionCount(Long value) {
        this.currentSessionCount = value;
    }

    /**
     * Gets the value of the cumulatedSessionCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCumulatedSessionCount() {
        return cumulatedSessionCount;
    }

    /**
     * Sets the value of the cumulatedSessionCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCumulatedSessionCount(Long value) {
        this.cumulatedSessionCount = value;
    }

    /**
     * Gets the value of the securityRejectedSessionCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSecurityRejectedSessionCount() {
        return securityRejectedSessionCount;
    }

    /**
     * Sets the value of the securityRejectedSessionCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSecurityRejectedSessionCount(Long value) {
        this.securityRejectedSessionCount = value;
    }

    /**
     * Gets the value of the rejectedSessionCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRejectedSessionCount() {
        return rejectedSessionCount;
    }

    /**
     * Sets the value of the rejectedSessionCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRejectedSessionCount(Long value) {
        this.rejectedSessionCount = value;
    }

    /**
     * Gets the value of the sessionTimeoutCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSessionTimeoutCount() {
        return sessionTimeoutCount;
    }

    /**
     * Sets the value of the sessionTimeoutCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSessionTimeoutCount(Long value) {
        this.sessionTimeoutCount = value;
    }

    /**
     * Gets the value of the sessionAbortCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSessionAbortCount() {
        return sessionAbortCount;
    }

    /**
     * Sets the value of the sessionAbortCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSessionAbortCount(Long value) {
        this.sessionAbortCount = value;
    }

    /**
     * Gets the value of the currentSubscriptionCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCurrentSubscriptionCount() {
        return currentSubscriptionCount;
    }

    /**
     * Sets the value of the currentSubscriptionCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCurrentSubscriptionCount(Long value) {
        this.currentSubscriptionCount = value;
    }

    /**
     * Gets the value of the cumulatedSubscriptionCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCumulatedSubscriptionCount() {
        return cumulatedSubscriptionCount;
    }

    /**
     * Sets the value of the cumulatedSubscriptionCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCumulatedSubscriptionCount(Long value) {
        this.cumulatedSubscriptionCount = value;
    }

    /**
     * Gets the value of the publishingIntervalCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPublishingIntervalCount() {
        return publishingIntervalCount;
    }

    /**
     * Sets the value of the publishingIntervalCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPublishingIntervalCount(Long value) {
        this.publishingIntervalCount = value;
    }

    /**
     * Gets the value of the securityRejectedRequestsCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSecurityRejectedRequestsCount() {
        return securityRejectedRequestsCount;
    }

    /**
     * Sets the value of the securityRejectedRequestsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSecurityRejectedRequestsCount(Long value) {
        this.securityRejectedRequestsCount = value;
    }

    /**
     * Gets the value of the rejectedRequestsCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRejectedRequestsCount() {
        return rejectedRequestsCount;
    }

    /**
     * Sets the value of the rejectedRequestsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRejectedRequestsCount(Long value) {
        this.rejectedRequestsCount = value;
    }

}
