//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for StructureDescription complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="StructureDescription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}DataTypeDescription"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StructureDefinition" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}StructureDefinition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StructureDescription", propOrder = {
    "structureDefinition"
})
public class StructureDescription
    extends DataTypeDescription
{

    @XmlElementRef(name = "StructureDefinition", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<StructureDefinition> structureDefinition;

    /**
     * Gets the value of the structureDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link StructureDefinition }{@code >}
     *     
     */
    public JAXBElement<StructureDefinition> getStructureDefinition() {
        return structureDefinition;
    }

    /**
     * Sets the value of the structureDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link StructureDefinition }{@code >}
     *     
     */
    public void setStructureDefinition(JAXBElement<StructureDefinition> value) {
        this.structureDefinition = value;
    }

}
