//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for TrustListMasks&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="TrustListMasks"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="None_0"/&gt;
 *     &lt;enumeration value="TrustedCertificates_1"/&gt;
 *     &lt;enumeration value="TrustedCrls_2"/&gt;
 *     &lt;enumeration value="IssuerCertificates_4"/&gt;
 *     &lt;enumeration value="IssuerCrls_8"/&gt;
 *     &lt;enumeration value="All_15"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "TrustListMasks")
@XmlEnum
public enum TrustListMasks {

    @XmlEnumValue("None_0")
    NONE_0("None_0"),
    @XmlEnumValue("TrustedCertificates_1")
    TRUSTED_CERTIFICATES_1("TrustedCertificates_1"),
    @XmlEnumValue("TrustedCrls_2")
    TRUSTED_CRLS_2("TrustedCrls_2"),
    @XmlEnumValue("IssuerCertificates_4")
    ISSUER_CERTIFICATES_4("IssuerCertificates_4"),
    @XmlEnumValue("IssuerCrls_8")
    ISSUER_CRLS_8("IssuerCrls_8"),
    @XmlEnumValue("All_15")
    ALL_15("All_15");
    private final String value;

    TrustListMasks(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static TrustListMasks fromValue(String v) {
        for (TrustListMasks c: TrustListMasks.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
