//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for UadpDataSetReaderMessageDataType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="UadpDataSetReaderMessageDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}DataSetReaderMessageDataType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GroupVersion" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="NetworkMessageNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="DataSetOffset" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/&gt;
 *         &lt;element name="DataSetClassId" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}Guid" minOccurs="0"/&gt;
 *         &lt;element name="NetworkMessageContentMask" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}UadpNetworkMessageContentMask" minOccurs="0"/&gt;
 *         &lt;element name="DataSetMessageContentMask" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}UadpDataSetMessageContentMask" minOccurs="0"/&gt;
 *         &lt;element name="PublishingInterval" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="ReceiveOffset" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="ProcessingOffset" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UadpDataSetReaderMessageDataType", propOrder = {
    "groupVersion",
    "networkMessageNumber",
    "dataSetOffset",
    "dataSetClassId",
    "networkMessageContentMask",
    "dataSetMessageContentMask",
    "publishingInterval",
    "receiveOffset",
    "processingOffset"
})
public class UadpDataSetReaderMessageDataType
    extends DataSetReaderMessageDataType
{

    @XmlElement(name = "GroupVersion")
    @XmlSchemaType(name = "unsignedInt")
    protected Long groupVersion;
    @XmlElement(name = "NetworkMessageNumber")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer networkMessageNumber;
    @XmlElement(name = "DataSetOffset")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer dataSetOffset;
    @XmlElement(name = "DataSetClassId")
    protected Guid dataSetClassId;
    @XmlElement(name = "NetworkMessageContentMask")
    @XmlSchemaType(name = "unsignedInt")
    protected Long networkMessageContentMask;
    @XmlElement(name = "DataSetMessageContentMask")
    @XmlSchemaType(name = "unsignedInt")
    protected Long dataSetMessageContentMask;
    @XmlElement(name = "PublishingInterval")
    protected Double publishingInterval;
    @XmlElement(name = "ReceiveOffset")
    protected Double receiveOffset;
    @XmlElement(name = "ProcessingOffset")
    protected Double processingOffset;

    /**
     * Gets the value of the groupVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getGroupVersion() {
        return groupVersion;
    }

    /**
     * Sets the value of the groupVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setGroupVersion(Long value) {
        this.groupVersion = value;
    }

    /**
     * Gets the value of the networkMessageNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNetworkMessageNumber() {
        return networkMessageNumber;
    }

    /**
     * Sets the value of the networkMessageNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNetworkMessageNumber(Integer value) {
        this.networkMessageNumber = value;
    }

    /**
     * Gets the value of the dataSetOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDataSetOffset() {
        return dataSetOffset;
    }

    /**
     * Sets the value of the dataSetOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDataSetOffset(Integer value) {
        this.dataSetOffset = value;
    }

    /**
     * Gets the value of the dataSetClassId property.
     * 
     * @return
     *     possible object is
     *     {@link Guid }
     *     
     */
    public Guid getDataSetClassId() {
        return dataSetClassId;
    }

    /**
     * Sets the value of the dataSetClassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Guid }
     *     
     */
    public void setDataSetClassId(Guid value) {
        this.dataSetClassId = value;
    }

    /**
     * Gets the value of the networkMessageContentMask property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNetworkMessageContentMask() {
        return networkMessageContentMask;
    }

    /**
     * Sets the value of the networkMessageContentMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNetworkMessageContentMask(Long value) {
        this.networkMessageContentMask = value;
    }

    /**
     * Gets the value of the dataSetMessageContentMask property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataSetMessageContentMask() {
        return dataSetMessageContentMask;
    }

    /**
     * Sets the value of the dataSetMessageContentMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataSetMessageContentMask(Long value) {
        this.dataSetMessageContentMask = value;
    }

    /**
     * Gets the value of the publishingInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPublishingInterval() {
        return publishingInterval;
    }

    /**
     * Sets the value of the publishingInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPublishingInterval(Double value) {
        this.publishingInterval = value;
    }

    /**
     * Gets the value of the receiveOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getReceiveOffset() {
        return receiveOffset;
    }

    /**
     * Sets the value of the receiveOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setReceiveOffset(Double value) {
        this.receiveOffset = value;
    }

    /**
     * Gets the value of the processingOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getProcessingOffset() {
        return processingOffset;
    }

    /**
     * Sets the value of the processingOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setProcessingOffset(Double value) {
        this.processingOffset = value;
    }

}
