//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for UpdateDataDetails complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="UpdateDataDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}HistoryUpdateDetails"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PerformInsertReplace" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}PerformUpdateType" minOccurs="0"/&gt;
 *         &lt;element name="UpdateValues" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfDataValue" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateDataDetails", propOrder = {
    "performInsertReplace",
    "updateValues"
})
public class UpdateDataDetails
    extends HistoryUpdateDetails
{

    @XmlElement(name = "PerformInsertReplace")
    @XmlSchemaType(name = "string")
    protected PerformUpdateType performInsertReplace;
    @XmlElementRef(name = "UpdateValues", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfDataValue> updateValues;

    /**
     * Gets the value of the performInsertReplace property.
     * 
     * @return
     *     possible object is
     *     {@link PerformUpdateType }
     *     
     */
    public PerformUpdateType getPerformInsertReplace() {
        return performInsertReplace;
    }

    /**
     * Sets the value of the performInsertReplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerformUpdateType }
     *     
     */
    public void setPerformInsertReplace(PerformUpdateType value) {
        this.performInsertReplace = value;
    }

    /**
     * Gets the value of the updateValues property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfDataValue }{@code >}
     *     
     */
    public JAXBElement<ListOfDataValue> getUpdateValues() {
        return updateValues;
    }

    /**
     * Sets the value of the updateValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfDataValue }{@code >}
     *     
     */
    public void setUpdateValues(JAXBElement<ListOfDataValue> value) {
        this.updateValues = value;
    }

}
