//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * &lt;p&gt;Java class for UserTokenType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="UserTokenType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Anonymous_0"/&gt;
 *     &lt;enumeration value="UserName_1"/&gt;
 *     &lt;enumeration value="Certificate_2"/&gt;
 *     &lt;enumeration value="IssuedToken_3"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "UserTokenType")
@XmlEnum
public enum UserTokenType {

    @XmlEnumValue("Anonymous_0")
    ANONYMOUS_0("Anonymous_0"),
    @XmlEnumValue("UserName_1")
    USER_NAME_1("UserName_1"),
    @XmlEnumValue("Certificate_2")
    CERTIFICATE_2("Certificate_2"),
    @XmlEnumValue("IssuedToken_3")
    ISSUED_TOKEN_3("IssuedToken_3");
    private final String value;

    UserTokenType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static UserTokenType fromValue(String v) {
        for (UserTokenType c: UserTokenType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
