//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.nodeset2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for UAMethod complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="UAMethod"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAInstance"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ArgumentDescription" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UAMethodArgument" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Executable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="UserExecutable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="MethodDeclarationId" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}NodeId" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UAMethod", propOrder = {
    "argumentDescription"
})
public class UAMethod
    extends UAInstance
{

    @XmlElement(name = "ArgumentDescription")
    protected List<UAMethodArgument> argumentDescription;
    @XmlAttribute(name = "Executable")
    protected Boolean executable;
    @XmlAttribute(name = "UserExecutable")
    protected Boolean userExecutable;
    @XmlAttribute(name = "MethodDeclarationId")
    protected String methodDeclarationId;

    /**
     * Gets the value of the argumentDescription property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the argumentDescription property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getArgumentDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UAMethodArgument }
     * </p>
     * 
     * 
     * @return
     *     The value of the argumentDescription property.
     */
    public List<UAMethodArgument> getArgumentDescription() {
        if (argumentDescription == null) {
            argumentDescription = new ArrayList<>();
        }
        return this.argumentDescription;
    }

    /**
     * Gets the value of the executable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isExecutable() {
        if (executable == null) {
            return true;
        } else {
            return executable;
        }
    }

    /**
     * Sets the value of the executable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExecutable(Boolean value) {
        this.executable = value;
    }

    /**
     * Gets the value of the userExecutable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUserExecutable() {
        if (userExecutable == null) {
            return true;
        } else {
            return userExecutable;
        }
    }

    /**
     * Sets the value of the userExecutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserExecutable(Boolean value) {
        this.userExecutable = value;
    }

    /**
     * Gets the value of the methodDeclarationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodDeclarationId() {
        return methodDeclarationId;
    }

    /**
     * Sets the value of the methodDeclarationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodDeclarationId(String value) {
        this.methodDeclarationId = value;
    }

}
