//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.company.opcua.nodeset2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for UANode complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="UANode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DisplayName" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}LocalizedText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}LocalizedText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Documentation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="References" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ListOfReferences" minOccurs="0"/&gt;
 *         &lt;element name="RolePermissions" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ListOfRolePermissions" minOccurs="0"/&gt;
 *         &lt;element name="Extensions" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ListOfExtensions" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="NodeId" use="required" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}NodeId" /&gt;
 *       &lt;attribute name="BrowseName" use="required" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}QualifiedName" /&gt;
 *       &lt;attribute name="WriteMask" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}WriteMask" default="0" /&gt;
 *       &lt;attribute name="UserWriteMask" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}WriteMask" default="0" /&gt;
 *       &lt;attribute name="AccessRestrictions" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}AccessRestriction" /&gt;
 *       &lt;attribute name="HasNoPermissions" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="SymbolicName" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}SymbolicName" /&gt;
 *       &lt;attribute name="ReleaseStatus" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ReleaseStatus" default="Released" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UANode", propOrder = {
    "displayName",
    "description",
    "category",
    "documentation",
    "references",
    "rolePermissions",
    "extensions"
})
@XmlSeeAlso({
    UAInstance.class,
    UAType.class
})
public class UANode {

    @XmlElement(name = "DisplayName")
    protected List<LocalizedText> displayName;
    @XmlElement(name = "Description")
    protected List<LocalizedText> description;
    @XmlElement(name = "Category")
    protected List<String> category;
    @XmlElement(name = "Documentation")
    protected String documentation;
    @XmlElement(name = "References")
    protected ListOfReferences references;
    @XmlElement(name = "RolePermissions")
    protected ListOfRolePermissions rolePermissions;
    @XmlElement(name = "Extensions")
    protected ListOfExtensions extensions;
    @XmlAttribute(name = "NodeId", required = true)
    protected String nodeId;
    @XmlAttribute(name = "BrowseName", required = true)
    protected String browseName;
    @XmlAttribute(name = "WriteMask")
    protected Long writeMask;
    @XmlAttribute(name = "UserWriteMask")
    protected Long userWriteMask;
    @XmlAttribute(name = "AccessRestrictions")
    protected Integer accessRestrictions;
    @XmlAttribute(name = "HasNoPermissions")
    protected Boolean hasNoPermissions;
    @XmlAttribute(name = "SymbolicName")
    protected String symbolicName;
    @XmlAttribute(name = "ReleaseStatus")
    protected ReleaseStatus releaseStatus;

    /**
     * Gets the value of the displayName property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the displayName property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDisplayName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedText }
     * </p>
     * 
     * 
     * @return
     *     The value of the displayName property.
     */
    public List<LocalizedText> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the description property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedText }
     * </p>
     * 
     * 
     * @return
     *     The value of the description property.
     */
    public List<LocalizedText> getDescription() {
        if (description == null) {
            description = new ArrayList<>();
        }
        return this.description;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the category property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the category property.
     */
    public List<String> getCategory() {
        if (category == null) {
            category = new ArrayList<>();
        }
        return this.category;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfReferences }
     *     
     */
    public ListOfReferences getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfReferences }
     *     
     */
    public void setReferences(ListOfReferences value) {
        this.references = value;
    }

    /**
     * Gets the value of the rolePermissions property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfRolePermissions }
     *     
     */
    public ListOfRolePermissions getRolePermissions() {
        return rolePermissions;
    }

    /**
     * Sets the value of the rolePermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfRolePermissions }
     *     
     */
    public void setRolePermissions(ListOfRolePermissions value) {
        this.rolePermissions = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfExtensions }
     *     
     */
    public ListOfExtensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfExtensions }
     *     
     */
    public void setExtensions(ListOfExtensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeId(String value) {
        this.nodeId = value;
    }

    /**
     * Gets the value of the browseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrowseName() {
        return browseName;
    }

    /**
     * Sets the value of the browseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrowseName(String value) {
        this.browseName = value;
    }

    /**
     * Gets the value of the writeMask property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getWriteMask() {
        if (writeMask == null) {
            return  0L;
        } else {
            return writeMask;
        }
    }

    /**
     * Sets the value of the writeMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWriteMask(Long value) {
        this.writeMask = value;
    }

    /**
     * Gets the value of the userWriteMask property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getUserWriteMask() {
        if (userWriteMask == null) {
            return  0L;
        } else {
            return userWriteMask;
        }
    }

    /**
     * Sets the value of the userWriteMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUserWriteMask(Long value) {
        this.userWriteMask = value;
    }

    /**
     * Gets the value of the accessRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccessRestrictions() {
        return accessRestrictions;
    }

    /**
     * Sets the value of the accessRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccessRestrictions(Integer value) {
        this.accessRestrictions = value;
    }

    /**
     * Gets the value of the hasNoPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHasNoPermissions() {
        if (hasNoPermissions == null) {
            return false;
        } else {
            return hasNoPermissions;
        }
    }

    /**
     * Sets the value of the hasNoPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasNoPermissions(Boolean value) {
        this.hasNoPermissions = value;
    }

    /**
     * Gets the value of the symbolicName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbolicName() {
        return symbolicName;
    }

    /**
     * Sets the value of the symbolicName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbolicName(String value) {
        this.symbolicName = value;
    }

    /**
     * Gets the value of the releaseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseStatus }
     *     
     */
    public ReleaseStatus getReleaseStatus() {
        if (releaseStatus == null) {
            return ReleaseStatus.RELEASED;
        } else {
            return releaseStatus;
        }
    }

    /**
     * Sets the value of the releaseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseStatus }
     *     
     */
    public void setReleaseStatus(ReleaseStatus value) {
        this.releaseStatus = value;
    }

}
